name: dev pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "primeira acao"
        run: echo "Hello World!!!"
